[package]
name = "midi_pulse"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "polite_ping"
path = "code/polite_ping.rs"

[[bin]]
name = "add_echo"
path = "code/add_echo.rs"

[[bin]]
name = "sampler"
path = "code/sampler.rs"

[dependencies]
midir = "0.10"
